package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/spoked/mcpd/internal/operations"
)

// PluginOverride is the store's answer about a plugin the configuration file
// declares.
//
// It exists because the file is frequently unwritable -- mounted read-only,
// on a read-only root filesystem, or regenerated by whatever provisioned the
// host -- so "remove it there instead" is a dead end rather than an
// instruction. The override layers over the file the same way a stored
// setting layers over a configured one, and for the same reason: the last
// person to decide should win, and the dashboard is where they decide.
type PluginOverride struct {
	Name string `json:"name"`
	// Removed reports that the file's declaration for this name is ignored.
	Removed bool `json:"removed"`
	// Enabled overrides the file's `enabled`, or is nil to follow it.
	Enabled *bool `json:"enabled,omitempty"`
	// DeclaredType is what the file said the instance was, as of the write.
	DeclaredType string `json:"declared_type"`
	Actor        string `json:"actor"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

// PluginDeclaration is what the configuration file says about an instance. It
// travels into the audit entry so a removal can be explained later even after
// the file has moved on -- or after the entry it removed has been deleted from
// the file by somebody tidying up.
type PluginDeclaration struct {
	Type     string
	Enabled  bool
	Required bool
}

// ErrNotRemoved reports a restore of a plugin that was not removed.
var ErrNotRemoved = errors.New("sqlite: that plugin is not removed")

// ErrPluginRemoved reports a change to a plugin whose declaration is
// overridden by a removal. Enabling something that is removed is not a state
// this represents: the answer is to restore it first.
var ErrPluginRemoved = errors.New("sqlite: that plugin is removed")

// PluginOverrideStore holds the dashboard's overrides of the configuration
// file's plugin declarations.
type PluginOverrideStore struct {
	db  *DB
	now func() time.Time
}

// NewPluginOverrideStore returns a store backed by db.
func NewPluginOverrideStore(db *DB, now func() time.Time) *PluginOverrideStore {
	if now == nil {
		now = time.Now
	}
	return &PluginOverrideStore{db: db, now: now}
}

// auditOverride appends one administrative act against a plugin declaration to
// the audit trail, inside the transaction that performed it.
//
// The trail rather than settings_history, on the same reasoning that puts a
// remote server's lifecycle there: this is not a value somebody changed, it is
// a decision about whether an integration is served at all, and it overrides
// what the deployment's own configuration says. Someone reading later needs to
// find it beside the operations that used the plugin, not in a list of
// settings edits.
func auditOverride(u *UnitOfWork, kind, actor, name, action string, detail map[string]any) error {
	body, err := json.Marshal(detail)
	if err != nil {
		return fmt.Errorf("sqlite: encode audit detail for %s: %w", kind, err)
	}
	return u.appendAudit(operations.AuditEntry{
		EventID: newEventID(),
		Kind:    kind,
		Plugin:  name,
		Action:  action,
		Actor:   actor,
		Detail:  body,
	})
}

// Remove records that the file's declaration for name is to be ignored.
//
// Idempotent: removing something already removed changes nothing and records
// nothing, because a trail that carries non-events is one nobody reads
// carefully.
func (s *PluginOverrideStore) Remove(
	ctx context.Context, actor, name string, declared PluginDeclaration,
) error {
	now := s.now().UnixMilli()
	return s.db.WriteTx(ctx, now, func(u *UnitOfWork) error {
		n, err := u.ExecAffected(`
			INSERT INTO plugin_overrides
				(name, removed, enabled, declared_type, actor, created_at, updated_at)
			VALUES (?, 1, NULL, ?, ?, ?, ?)
			ON CONFLICT (name) DO UPDATE SET
				removed       = 1,
				declared_type = excluded.declared_type,
				actor         = excluded.actor,
				updated_at    = excluded.updated_at
			WHERE plugin_overrides.removed = 0`,
			name, declared.Type, actor, now, now)
		if err != nil {
			return fmt.Errorf("sqlite: remove plugin declaration: %w", err)
		}
		if n == 0 {
			return nil
		}
		return auditOverride(u, "plugin.removed", actor, name, "remove", map[string]any{
			"source":            "configuration file",
			"declared_type":     declared.Type,
			"declared_enabled":  declared.Enabled,
			"declared_required": declared.Required,
			"file_changed":      false,
		})
	})
}

// Restore puts a removed plugin back under the file's declaration.
//
// The row goes when the removal was the only thing it carried, which is what
// the table's CHECK requires of a row that overrides nothing.
func (s *PluginOverrideStore) Restore(ctx context.Context, actor, name string) error {
	now := s.now().UnixMilli()
	return s.db.WriteTx(ctx, now, func(u *UnitOfWork) error {
		dropped, err := u.ExecAffected(`
			DELETE FROM plugin_overrides
			 WHERE name = ? AND removed = 1 AND enabled IS NULL`, name)
		if err != nil {
			return fmt.Errorf("sqlite: restore plugin declaration: %w", err)
		}
		kept, err := u.ExecAffected(`
			UPDATE plugin_overrides
			   SET removed = 0, actor = ?, updated_at = ?
			 WHERE name = ? AND removed = 1`, actor, now, name)
		if err != nil {
			return fmt.Errorf("sqlite: restore plugin declaration: %w", err)
		}
		if dropped+kept == 0 {
			return ErrNotRemoved
		}
		return auditOverride(u, "plugin.restored", actor, name, "restore", map[string]any{
			"source": "configuration file",
			// Said explicitly because it is the question the entry answers:
			// the plugin is back under whatever the file declares, not under
			// what it declared when the removal happened.
			"restored_to": "the configuration file's declaration",
		})
	})
}

// SetEnabled overrides the file's `enabled` for a declared plugin.
func (s *PluginOverrideStore) SetEnabled(
	ctx context.Context, actor, name string, declared PluginDeclaration, enabled bool,
) error {
	now := s.now().UnixMilli()
	return s.db.WriteTx(ctx, now, func(u *UnitOfWork) error {
		n, err := u.ExecAffected(`
			INSERT INTO plugin_overrides
				(name, removed, enabled, declared_type, actor, created_at, updated_at)
			VALUES (?, 0, ?, ?, ?, ?, ?)
			ON CONFLICT (name) DO UPDATE SET
				enabled       = excluded.enabled,
				declared_type = excluded.declared_type,
				actor         = excluded.actor,
				updated_at    = excluded.updated_at
			WHERE plugin_overrides.removed = 0
			  AND plugin_overrides.enabled IS NOT excluded.enabled`,
			name, boolToInt(enabled), declared.Type, actor, now, now)
		if err != nil {
			return fmt.Errorf("sqlite: override plugin enabled: %w", err)
		}
		if n == 0 {
			// Either it is removed, which the guard refused, or it already
			// said this. Distinguish them rather than reporting success for
			// the first.
			var removed int
			switch err := u.queryRow(
				`SELECT removed FROM plugin_overrides WHERE name = ?`, name,
			).Scan(&removed); {
			case errors.Is(err, sql.ErrNoRows):
				// No row and no insert means the insert's own guard did not
				// fire; nothing else can produce this, so treat it as the
				// no-op it is.
				return nil
			case err != nil:
				return err
			case removed == 1:
				return ErrPluginRemoved
			}
			return nil
		}
		kind := "plugin.disabled"
		if enabled {
			kind = "plugin.enabled"
		}
		return auditOverride(u, kind, actor, name, "set_enabled", map[string]any{
			"source":           "configuration file",
			"enabled":          enabled,
			"declared_enabled": declared.Enabled,
		})
	})
}

// List returns every override, by name.
func (s *PluginOverrideStore) List(ctx context.Context) ([]PluginOverride, error) {
	rows, err := s.db.Reader().QueryContext(ctx, `
		SELECT name, removed, enabled, declared_type, actor, created_at, updated_at
		  FROM plugin_overrides
		 ORDER BY name`)
	if err != nil {
		return nil, fmt.Errorf("sqlite: list plugin overrides: %w", err)
	}
	defer rows.Close()

	out := []PluginOverride{}
	for rows.Next() {
		var o PluginOverride
		var removed int
		var enabled sql.NullInt64
		if err := rows.Scan(&o.Name, &removed, &enabled, &o.DeclaredType,
			&o.Actor, &o.CreatedAt, &o.UpdatedAt); err != nil {
			return nil, err
		}
		o.Removed = removed == 1
		if enabled.Valid {
			on := enabled.Int64 == 1
			o.Enabled = &on
		}
		out = append(out, o)
	}
	return out, rows.Err()
}
